### ISSUE TITLE
Bug in FxTagTracker::UpdateTagHistory

### ISSUE THREAD

**Issue by pe-bo** [microsoft/Windows-Driver-Frameworks#15]
I found an error in the FxTagTracker :: UpdateTagHistory method. If the m_CurRefHistory counter overflows, the pos% TAG_HISTORY_DEPTH value becomes negative and points outside the m_TagHistory array. This causes BugCheck.

See https://github.com/microsoft/Windows-Driver-Frameworks/blob/168a37f03e6498f483cb8eddf700b62680ec8d1d/src/framework/shared/object/fxtagtracker.cpp#L177

**Comment by wm1** [comment]
Right after it there is `pos %= TAG_HISTORY_DEPTH;` and comment that it would never be negative.
