### ISSUE TITLE
Bug in FxTagTracker::UpdateTagHistory (reopen)

### ISSUE THREAD

**Issue by pe-bo** [microsoft/Windows-Driver-Frameworks#16]
This issue is based on now closed #15, I am not able to reopen original issue.

"I found an error in the FxTagTracker :: UpdateTagHistory method. If the m_CurRefHistory counter overflows, the pos% TAG_HISTORY_DEPTH value becomes negative and points outside the m_TagHistory array. This causes BugCheck."

This problem is REAL and I tracked it down under WinDbg debugger. This problem occurs if tag tracing is enabled in the registry and the object is frequently referenced and dereferenced.

The explanation from wm1 user is meaningless. The m_CurRefHistory counter can overflows, of course. And pos variable has LONG data type which is signed. Thus pos can be negative. The C operator % returns negative remainder for negative dividend, see e.g.
https://docs.microsoft.com/en-us/cpp/cpp/multiplicative-operators-and-the-modulus-operator?view=msvc-160

The comment in the original source is wrong. There is simple solution: use ULONG data type for pos variable.

**Comment by wm1** [comment]
You're right. I did not catch the issue in the first time. The bug is fixed internally now.
