### ISSUE TITLE
Typo in comment

### ISSUE THREAD

**Issue by grimbeaver** [microsoft/Windows-Driver-Frameworks#19]
Incredibly minor, but in a comment in pnpstatemachine.cpp "machine" is misspelled as "machien".

https://github.com/microsoft/Windows-Driver-Frameworks/blob/d9f66ca7ede31bc0745daad5c6f2aedb53795969/src/framework/shared/irphandlers/pnp/pnpstatemachine.cpp#L1514

**Comment by wm1** [comment]
fixed in PnpEventHardwareAvailablePowerPolicyFailed
