### ISSUE TITLE
Preprocessor usage bug in fxrequestbuffer.hpp

### ISSUE THREAD

**Issue by brettw** [microsoft/Windows-Driver-Frameworks#20]
The file src/framework/shared/inc/private/common/fxrequestbuffer.hpp contains this block near the bottom:

```
#if ((FX_CORE_MODE)==(FX_CORE_KERNEL_MODE))
#include "FxRequestBufferKm.hpp"
#else if ((FX_CORE_MODE)==(FX_CORE_USER_MODE))
#include "FxRequestBufferUm.hpp"
#endif
```

The #else line isn't valid C/C++. The author meant #elif. I think the compiler is treating this as an #else followed by extra tokens it ignores.

You just need to change "#else if" -> "#elif"

**Comment by wm1** [comment]
Thanks, I will fix it in next release
