### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Microsoft/Windows-Driver-Frameworks#3]
I would like to point out that identifiers like "[`_WDF_DRIVER_CONFIG_V1_0`](https://github.com/Microsoft/Windows-Driver-Frameworks/blob/058a020ccd9db55bb8406323e78a6849e00cc5d4/src/framework/shared/core/coreprivshared.hpp#L171)" and "[`_WDF_INTERRUPT_INFO_V1_7`](https://github.com/Microsoft/Windows-Driver-Frameworks/blob/058a020ccd9db55bb8406323e78a6849e00cc5d4/src/framework/shared/irphandlers/pnp/pnppriv.hpp#L450)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jmrossy** [comment]
Thanks for pointing this out. The WDF development team has decided not to address this for now but we'll keep it in mind as a desirable refactoring goal.
