### ISSUE TITLE
_IRQL_requires_max_ missing

### ISSUE THREAD

**Issue by maxtruxa** [microsoft/Windows-Driver-Frameworks#4]
`_IRQL_requires_max_` is missing from a few methods. IRQL requirements for these functions are documented in the MSDN though.

[`WdfObjectAllocateContext`](https://github.com/Microsoft/Windows-Driver-Frameworks/blob/master/src/publicinc/wdf/kmdf/1.15/wdfobject.h#L585) should have `_IRQL_requires_max_(DISPATCH_LEVEL)` [MSDN](https://msdn.microsoft.com/en-us/library/windows/hardware/ff548723%28v=vs.85%29.aspx) (and possibly `_Must_inspect_result_`)
[`WdfObjectReferenceActual`](https://github.com/Microsoft/Windows-Driver-Frameworks/blob/master/src/publicinc/wdf/kmdf/1.15/wdfobject.h#L641) should have `_IRQL_requires_max_(DISPATCH_LEVEL)` [MSDN](https://msdn.microsoft.com/en-us/library/windows/hardware/ff548760%28v=vs.85%29.aspx)
[`WdfObjectDereferenceActual`](https://github.com/Microsoft/Windows-Driver-Frameworks/blob/master/src/publicinc/wdf/kmdf/1.15/wdfobject.h#L676) should have `_IRQL_requires_max_(DISPATCH_LEVEL)` [MSDN](https://msdn.microsoft.com/en-us/library/windows/hardware/ff548743%28v=vs.85%29.aspx)

This list is non-exhaustive. If desired I can keep adding functions with missing declarations.

**Comment by pankajbharti** [comment]
Thanks for bringing this to our attention. We are looking at this. 

Note that the NTSTATUS does already has an implicit _Must_inspect_result_ annotation.

Thanks

**Comment by tandasat** [comment]
@pankajbharti I have not been able to find documentation or annotation about that NTSTATUS does already has an implicit Must_inspect_result annotation. Can you please let me where I can find this?

**Comment by wm1** [comment]
All API should have been properly annotated for IRQL requirement in latest header WDF version. If you fine anything missing, please report again.

Note the fix is not back ported to older version of WDF headers. That is, if you check v15 headers, they are still missing the IRQL annotation.
