### ISSUE TITLE
src/framework/kmdf/src/core/tracing.cpp pragma typo's

### ISSUE THREAD

**Issue by thatnerdjosh** [microsoft/Windows-Driver-Frameworks#6]
"Recommended" is mis-spelled in two of the pragma declarations in this file

**Comment by kumraj** [comment]
Thanks for bringing this up. These will be fixed in the next release.

-kumar

**Comment by Charnarongthumwan** [comment]
Good

**Comment by wm1** [comment]
No longer exists.
