### ISSUE TITLE
The Markup for CONTRIBUTING.md is incorrect

### ISSUE THREAD

**Issue by alexbuzzbee** [microsoft/Windows-Driver-Frameworks#7]
In `/CONTRIBUTING.md`, there are three issues with the Markdown formatting:

1. The highest-level heading in the file is a `##`, which is a second-level heading; the second heading is a `###`, which is a third-level heading.
2. Markdown headings require a space between the `#` and the text of the heading.
3. Markdown paragraphs require a blank line separating them.

For example:

```markdown
# Heading 1

Content 1

## Heading 2

Content 2.1

Content 2.2
```

Renders as:

# Heading 1

Content 1

## Heading 2

Content 2.1

Content 2.2

**Comment by wm1** [comment]
Fixed, thanks,
