### ISSUE TITLE
Licensing confusion

### ISSUE THREAD

**Issue by zfigura** [microsoft/Windows-Driver-Frameworks#8]
The README states that WDF is licensed under the MIT license. However, a large number of the files distributed with WDF contain the provision "All rights reserved", which may be easily taken to contradict the rights that the MIT license expressly grants. Can this please be clarified; i.e. are these files under a stricter license than the rest of the source, or is the entire source intended to be taken as under the MIT license?

Thanks,
Zebediah Figura

**Comment by wm1** [comment]
I am not a lawyer. Similar discussion can be found at PowerShell/PowerShell#2129.
